### ISSUE TITLE
People evaluating this might not be able to build

### ISSUE THREAD

**Issue by 5HT2** [sinaladel/ponker#2]
I'm assuming this is a school project or something, just wanted to point out I'm unable to build and I get 
```
 problem was found with the configuration of task ':app:lint'.
> No value has been specified for property 'lintClassPath'.
```
so you should try building on a clean machine from just a git clone of this repo
or maybe i'm just dumb and i broke something who knows
i ran `./gradlew build`

**Comment by EmotionalLove** [comment]
It's an android studio project

**Comment by 5HT2** [comment]
o i'm dumb
